### ISSUE TITLE
Error when fuzzing with AFL 

### ISSUE THREAD

**Issue by xupeng1231** [sslab-gatech/qsym#105]
When fuzzing with afl, I encountered with a problem, it seems that qsym may handle an input deleted by AFL.
The following is the error point:
```
DEBUG:qsym.afl:Run qsym: input=/mnt/hgfs/CCFuzzerData/output/afl-master/queue/id:003846,sync:qsym,src:000683,+cov
DEBUG:qsym.Executor:Executing timeout -k 5 90 /home/sentosa/.local/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/sentosa/.local/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/tmpWe02eh/qsym-out-240/pin.log -i /mnt/hgfs/CCFuzzerData/output/qsym/.cur_input -f 1 -o /tmp/tmpWe02eh/qsym-out-240 -l 1 -b /mnt/hgfs/CCFuzzerData/output/qsym/bitmap -- /home/sentosa/CCWork/software/qsym/ImageMagick_qsym/utilities/magick convert /mnt/hgfs/CCFuzzerData/output/qsym/.cur_input /dev/null
DEBUG:qsym.afl:Total=40 s, Emulation=39 s, Solver=0 s, Return=1
DEBUG:qsym.afl:Generate 7 testcases
DEBUG:qsym.afl:0 testcases are new
DEBUG:qsym.afl:Run qsym: input=/mnt/hgfs/CCFuzzerData/output/afl-master/queue/id:003857,sync:qsym,src:000768,+cov
DEBUG:qsym.Executor:Executing timeout -k 5 90 /home/sentosa/.local/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/sentosa/.local/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/tmpWe02eh/qsym-out-241/pin.log -i /mnt/hgfs/CCFuzzerData/output/qsym/.cur_input -f 1 -o /tmp/tmpWe02eh/qsym-out-241 -l 1 -b /mnt/hgfs/CCFuzzerData/output/qsym/bitmap -- /home/sentosa/CCWork/software/qsym/ImageMagick_qsym/utilities/magick convert /mnt/hgfs/CCFuzzerData/output/qsym/.cur_input /dev/null
DEBUG:qsym.afl:Total=93 s, Emulation=40 s, Solver=52 s, Return=124
DEBUG:qsym.afl:Creating: /mnt/hgfs/CCFuzzerData/output/qsym/queue/id:000887,src:id:003857
DEBUG:qsym.afl:Creating: /mnt/hgfs/CCFuzzerData/output/qsym/queue/id:000888,src:id:003857
DEBUG:qsym.afl:Creating: /mnt/hgfs/CCFuzzerData/output/qsym/queue/id:000889,src:id:003857
DEBUG:qsym.afl:Generate 15 testcases
DEBUG:qsym.afl:3 testcases are new
Traceback (most recent call last):
  File "/home/sentosa/qsym/bin/run_qsym_afl.py", line 47, in <module>
    main()
  File "/home/sentosa/qsym/bin/run_qsym_afl.py", line 41, in main
    e.run()
  File "/home/sentosa/.local/lib/python2.7/site-packages/qsym/afl.py", line 349, in run
    files = self.sync_files()
  File "/home/sentosa/.local/lib/python2.7/site-packages/qsym/afl.py", line 219, in sync_files
    reverse=True)
  File "/usr/lib/python2.7/functools.py", line 87, in __lt__
    return mycmp(self.obj, other.obj) < 0
  File "/home/sentosa/.local/lib/python2.7/site-packages/qsym/afl.py", line 47, in testcase_compare
    b_score = get_score(b)
  File "/home/sentosa/.local/lib/python2.7/site-packages/qsym/afl.py", line 40, in get_score
    score3 = -os.path.getsize(testcase)
  File "/usr/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/mnt/hgfs/CCFuzzerData/output/afl-master/queue/.fuse_hidden0027011b000002e1'

```

**Comment by xupeng1231** [comment]
It seems that files in the format of` .fuse_hiddenxxxxx` should be filtered out, because it is not a normal input entry. Please refer to [https://askubuntu.com/questions/493198/what-is-a-fuse-hidden-file-and-why-do-they-exist](https://askubuntu.com/questions/493198/what-is-a-fuse-hidden-file-and-why-do-they-exist)

**Comment by insuyun** [comment]
Hi, @xupeng1231. In your environment, could you get this error deterministically?
Then can you test https://github.com/sslab-gatech/qsym/commit/e0bf2d32db174e05d4dc767883bfb9d8b175706b?

**Comment by xupeng1231** [comment]
Yes, I get this error deterministically. It often occurs after the fuzzer start up for ten minutes.
I also have a proof in AFL's code, it filter out the file whose name starts with '.' in function `sync_fuzzers`
The following is the related code of AFL.
```

    while ((qd_ent = readdir(qd))) {

      u8* path;
      s32 fd;
      struct stat st;

      if (qd_ent->d_name[0] == '.' ||
          sscanf(qd_ent->d_name, CASE_PREFIX "%06u", &syncing_case) != 1 || 
          syncing_case < min_accept) continue;

      /* OK, sounds like a new one. Let's give it a try. */

      if (syncing_case >= next_min_accept)
        next_min_accept = syncing_case + 1;

```

**Comment by xupeng1231** [comment]
@insuyun With the same way as you have done，I have patched qsym in my environment, and it become very stable.
