### ISSUE TITLE
No file found while running qsym

### ISSUE THREAD

**Issue by natalie13m** [sslab-gatech/qsym#30]
Hi guys,

I tried to run qsym in docker with the command as below, however it failed everytime. My guess if qsym cannot find /tmp/tmpzyrIYP and the new inputs in it. However I can get access to those files under root. I also tried to run qsym command in root but it didn't work. Any idea why this happened?

```sh
root@a0c7f4708328:/mnt/Research/afl_qsym_test/qsym# bin/run_qsym_afl.py -a afl-slave -o /mnt/Research/afl_qsym_test/base64/findings/ -n qsym -- /mnt/Research/afl_qsym_test/base64/base64 -d @@
DEBUG:qsym.afl:Temp directory=/tmp/tmpzyrIYP
DEBUG:qsym.afl:Run qsym: input=/mnt/Research/afl_qsym_test/base64/findings/afl-slave/queue/id:000068,src:000036+000050,op:splice,rep:32,+cov
DEBUG:qsym.Executor:Executing timeout -k 5 90 /usr/local/lib/python2.7/dist-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /usr/local/lib/python2.7/dist-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/tmpzyrIYP/qsym-out-0/pin.log -i /mnt/Research/afl_qsym_test/base64/findings/qsym/.cur_input -f 1 -o /tmp/tmpzyrIYP/qsym-out-0 -l 1 -b /mnt/Research/afl_qsym_test/base64/findings/qsym/bitmap -- /mnt/Research/afl_qsym_test/base64/base64 -d /mnt/Research/afl_qsym_test/base64/findings/qsym/.cur_input
DEBUG:qsym.afl:Total=11 s, Emulation=9 s, Solver=1 s, Return=0
Traceback (most recent call last):
  File "bin/run_qsym_afl.py", line 47, in <module>
    main()
  File "bin/run_qsym_afl.py", line 41, in main
    e.run()
  File "/usr/local/lib/python2.7/dist-packages/qsym/afl.py", line 356, in run
    self.run_file(fp)
  File "/usr/local/lib/python2.7/dist-packages/qsym/afl.py", line 376, in run_file
    if not self.minimizer.check_testcase(testcase):
  File "/usr/local/lib/python2.7/dist-packages/qsym/minimizer.py", line 64, in check_testcase
    proc = sp.Popen(cmd, stdin=sp.PIPE, stdout=devnull, stderr=devnull)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by natalie13m** [comment]
Well I did use the same docker image to run both AFL and qsym and I succeeded before. It's really strange that I cannot do it now.

**Comment by jakkdu** [comment]
Please check your `fuzzer-stats` in your AFL output directory.
QSYM gets the AFL directory from that file to find `afl-showmap`.
Thanks.

**Comment by natalie13m** [comment]
I think I get the reason why this went wrong: I used absolute path instead of relevant path in both AFL's and QSYM's command lines and then it worked. Anyway, problem solved and thanks a lot for your help!

**Comment by jakkdu** [comment]
My pleasure.
